defmodule Brain.Commands do
  @moduledoc """
  Routes incoming Portuguese text commands to the relevant Brain context.

  This module intentionally stays free of HTTP and WhatsApp concerns. It is the
  stable entry point used by the webhook while shopping-list and reminder logic
  live in their own context modules.
  """

  alias Brain.Reminders
  alias Brain.ShoppingList

  @help_text """
             [BOT] Comandos que conheço:
             🛒 Compras
             - adiciona <item> ou adiciona <item>, <item>
             - remove <item>
             - lista
             - limpar lista

             🏠 Despensa
             - tenho <item> ou tenho <item>, <item>
             - usei <item>
             - o que tenho na despensa?
             - limpar despensa

             🍽️ Menu da Semana
             - faz-me o menu da semana
             - receita de <dia>
             - gostei de <prato> / não gostei de <prato>

             🔔 Lembretes
             - lembrar de <tarefa> logo
             - lembrar de <tarefa> amanhã
             - lembrar de <tarefa> daqui a N minutos/horas/dias/semanas

             ❔ Ajuda
             - ajuda
             """
             |> String.trim_trailing()

  def handle(text, sender, group_id \\ nil)

  def handle(text, sender, group_id) when is_binary(text) do
    trimmed_raw = String.trim(text)
    trimmed_lower = String.downcase(trimmed_raw)

    if bot_reply?(trimmed_lower) do
      :ignore
    else
      route(trimmed_raw, trimmed_lower, sender, group_id)
    end
  end

  def handle(_text, _sender, _group_id), do: :ignore

  defp route(trimmed_raw, trimmed_lower, sender, group_id, llm_attempted? \\ false) do
    cond do
      help_command?(trimmed_lower) ->
        {:reply, @help_text}

      reminder_command?(trimmed_lower) ->
        Reminders.schedule_from_text(trimmed_raw, sender, group_id)

      trimmed_lower in ["lista", "mostrar lista", "ver lista", "list", "show list"] ->
        ShoppingList.list()

      trimmed_lower in ["limpar", "limpar lista", "clear", "clear list"] ->
        ShoppingList.clear()

      String.starts_with?(trimmed_lower, "adicionar") ->
        trimmed_raw
        |> extract_argument("adicionar")
        |> ShoppingList.add(sender)

      String.starts_with?(trimmed_lower, "adiciona") ->
        trimmed_raw
        |> extract_argument("adiciona")
        |> ShoppingList.add(sender)

      String.starts_with?(trimmed_lower, "add") ->
        trimmed_raw
        |> extract_argument("add")
        |> ShoppingList.add(sender)

      String.starts_with?(trimmed_lower, "remover") ->
        trimmed_raw
        |> extract_argument("remover")
        |> ShoppingList.remove()

      String.starts_with?(trimmed_lower, "remove") ->
        trimmed_raw
        |> extract_argument("remove")
        |> ShoppingList.remove()

      true and not llm_attempted? ->
        fallback_to_llm(trimmed_raw, sender, group_id)

      true ->
        :ignore
    end
  end

  defp fallback_to_llm(trimmed_raw, sender, group_id) do
    case Brain.LLM.CommandInterpreter.interpret(trimmed_raw) do
      {:ok, {:add_pantry_items, items}} ->
        Brain.Pantry.add_many(items, sender)

      {:ok, {:remove_pantry_item, item}} ->
        Brain.Pantry.remove(item)

      {:ok, :list_pantry} ->
        Brain.Pantry.list()

      {:ok, :clear_pantry} ->
        Brain.Pantry.clear()

      {:ok, {:generate_menu, constraints}} ->
        Brain.MenuPlanner.generate(constraints, group_id)

      {:ok, {:get_recipe, item}} ->
        Brain.MenuPlanner.get_recipe(item, group_id)

      {:ok, {:rate_meal, meal, sentiment}} ->
        sentiment_text = if sentiment == "like", do: "gostei", else: "não gostei"

        case Brain.MealFeedback.create(%{
               group_id: group_id,
               meal_name: meal,
               sentiment: sentiment,
               raw_text: trimmed_raw
             }) do
          {:ok, _feedback} ->
            {:reply, "[BOT] 📝 Registado: #{sentiment_text} de #{meal}."}

          {:error, _changeset} ->
            {:reply, "[BOT] 😕 Não consegui registar o teu feedback."}
        end

      {:ok, canonical_command} ->
        route(canonical_command, String.downcase(canonical_command), sender, group_id, true)

      :ignore ->
        :ignore
    end
  end

  defp bot_reply?(trimmed_lower) do
    # Every reply generated by the brain (commands, invoices, menu, reminders)
    # starts with the "[BOT]" marker. Only that marker is reliable — phrases
    # like "por favor ...", "lembrete ..." or a bare emoji can be legitimate
    # user messages and must not be dropped.
    String.starts_with?(trimmed_lower, ["[bot]"])
  end

  defp reminder_command?(trimmed_lower) do
    String.starts_with?(trimmed_lower, [
      "lembrar de",
      "lembrar-me de",
      "lembra de",
      "lembra-me de",
      "lembra-nos de"
    ])
  end

  defp help_command?(trimmed_lower) do
    trimmed_lower in ["ajuda", "help", "comandos", "ver comandos"]
  end

  defp extract_argument(raw_text, command_prefix) do
    offset = String.length(command_prefix)
    String.slice(raw_text, offset..-1//1) |> String.trim()
  end
end
